name: datalab_ml_iot
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - rise
  - pip
  - jupyter
  - jupyter_nbextensions_configurator
  - scikit-learn
  - make
  - pip:
    - jupyter-contrib-nbextensions
    - tensorflow-gpu==1.15
    - kaggle==1.5.6
    - pip install j2cli[yaml]